### Day 11
Part 1: Given the starting energy levels of the dumbo octopuses in your cavern, simulate 100 steps. How many total flashes are there after 100 steps?

In [1]:
# let's create some functions

import numpy as np

def execute_flash(in_arr, r, c):
    """
    Add 1 to all 8 surrounding neighbours in an array 
    This ended up as a bit of a bodge job, could be improved...
    """
    in_arr[r,c] -= 1  # first subtract 1 from that point, then add 1 to it and neighbours
    
    dr = dc = 2
    if r-1 < 0: r = dr = 1  # deal with the edge cases (don't want to have negative values in slices)
    if c-1 < 0: c = dc = 1

    sub_arr = in_arr[r-1:r+dr, c-1:c+dc]   # create sub array of cell and neighbours (respecting edge cases)
    flash_add = np.ones(sub_arr.shape, dtype=int)  # create array of 1s
    in_arr[r-1:r+dr, c-1:c+dc] = sub_arr + flash_add  # add array of 1s to sub array and replace those cells in in array

    return in_arr


def execute_steps(in_string, n_steps, stop_all_flash=False):
    """
    Convert string to array, the for each step: add 1 to all cells in array, and flash octopuses
    Report total number of flashes and return final array
    """
    arr = np.array([list(i) for i in in_string.split("\n")], dtype=int)
    n_flashed = 0
    
    for step in range(n_steps):
        # increase all cells by 1
        arr += 1
        
        # create flash array with zeros
        flash_arr = np.zeros(shape=arr.shape, dtype=int)
        flash_arr[arr > 9] = 1
        octopuses_flashing = np.sum(flash_arr == 1)
        n_flashed += octopuses_flashing  # add to total sum

        # if octopuses need to flash
        while octopuses_flashing > 0:           
            # get coords for flashing
            flash_rows, flash_cols = np.where(flash_arr == 1)

            # flash those octopuses
            for row, col in zip(flash_rows, flash_cols):
                arr = execute_flash(arr, row, col) 
                
            # check again at end of loop
            flash_arr[arr > 9] += 1
            octopuses_flashing = np.sum(flash_arr == 1)
            n_flashed += octopuses_flashing  # add to total sum
    
        # set any values above 10 to 0
        arr[arr > 9] = 0
        
        # for part 2
        if stop_all_flash:
            if np.sum(flash_arr == 0) == 0:
                print(f"Stopped at step {step+1} as all octopuses flashed!")
                return arr
            
    print(f"The total number of octopus flashes is {n_flashed}")
    return arr

In [2]:
day_11_test = """5483143223
2745854711
5264556173
6141336146
6357385478
4167524645
2176841721
6882881134
4846848554
5283751526"""

In [3]:
# run on test data - should be: 
# 0 after 1 step, 35 after 2 steps, 2014 after 10 steps and 1656 after 100 steps
steps = [1, 2, 10, 100]
for s in steps:
    print(f"After {s} steps: ", end="")
    _ = execute_steps(day_11_test, s)

After 1 steps: The total number of octopus flashes is 0
After 2 steps: The total number of octopus flashes is 35
After 10 steps: The total number of octopus flashes is 204
After 100 steps: The total number of octopus flashes is 1656


In [4]:
# load and run on full data
with open("inputs/day_11.txt") as f:
    day_11 = f.read()
    
execute_steps(day_11, 100)

The total number of octopus flashes is 1675


array([[7, 9, 0, 0, 0, 0, 8, 6, 5, 5],
       [9, 3, 5, 0, 0, 4, 2, 8, 6, 5],
       [2, 2, 3, 6, 3, 2, 1, 1, 8, 6],
       [2, 2, 2, 4, 1, 1, 1, 1, 1, 8],
       [3, 3, 2, 3, 5, 1, 1, 1, 1, 1],
       [1, 4, 2, 2, 3, 5, 1, 1, 1, 1],
       [1, 4, 2, 2, 2, 3, 5, 1, 1, 1],
       [8, 3, 2, 2, 2, 2, 3, 6, 1, 1],
       [6, 8, 2, 2, 2, 2, 3, 6, 3, 2],
       [5, 6, 8, 2, 2, 2, 3, 0, 0, 2]])

Part 2: If you can calculate the exact moments when the octopuses will all flash simultaneously, you should be able to navigate through the cavern. What is the first step during which all octopuses flash?

In [5]:
# edited the functions above for part 2
# check on test data, should stop after step 195
execute_steps(day_11_test, 200, stop_all_flash=True)

Stopped at step 195 as all octopuses flashed!


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [6]:
# run on full data, should stop after step 195
execute_steps(day_11, 1000, stop_all_flash=True)

Stopped at step 515 as all octopuses flashed!


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

#### Working
Could edit execute_flash function above using this function to find neighbours, rather than array slicing

In [7]:
# make a function to return neighbour coordinates - adpated from day 9
def neighbours(in_arr, r, c):   # r = row, c = column
    nr, nc = in_arr.shape   # number of rows and columns
    neighbour_coords = []

    if r+1 < nr:
        neighbour_coords.append((r+1,c))
    if r-1 >= 0:
        neighbour_coords.append((r-1,c))
    if c+1 < nc:
        neighbour_coords.append((r,c+1))
    if c-1 >= 0:
        neighbour_coords.append((r,c-1))
    if r+1 < nr and c+1 < nc:
        neighbour_coords.append((r+1,c+1))
    if r+1 < nr and c-1 >= 0:
        neighbour_coords.append((r+1,c-1))
    if r-1 >= 0 and c-1 >= 0:
        neighbour_coords.append((r-1,c-1))
    if r-1 >= 0 and c+1 < nc:
        neighbour_coords.append((r-1,c+1))

    return neighbour_coords