### Day 4

Part 1: Figure out which board will win first. What will your final score be if you choose that board?

In [1]:
import numpy as np

In [2]:
# function for part 1 - load data, track boards - stop when 1 board has won and calculate sum and product
def calc_winning_score(nums_string, boards_string):
    
    nums = [int(x) for x in nums_string.split(",")]
    
    boards_str_split = [y.split() for x in boards_string.split("\n\n") for y in x.split("\n")]
    boards = np.array(boards_str_split, dtype=int).reshape(-1,5,5)

    boards_tracker = np.zeros(shape=boards.shape, dtype=int)

    for num in nums:
        for i in range(boards.shape[0]):
            boards_tracker[i] += boards[i] == num

            if max(boards_tracker[i].sum(axis=0)) == 5 or max(boards_tracker[i].sum(axis=1)) == 5:
                print(f"board number {i} has won:")
                print(boards[i])
                print(boards_tracker[i])
                unmarked_sum = sum(boards[i][boards_tracker[i] == 0])
                print(unmarked_sum)
                product = unmarked_sum * num
                return product

In [3]:
# load test data
day_4_test_nums = '7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1'

day_4_test_boards = """22 13 17 11  0
 8  2 23  4 24
21  9 14 16  7
 6 10  3 18  5
 1 12 20 15 19

 3 15  0  2 22
 9 18 13 17  5
19  8  7 25 23
20 11 10 24  4
14 21 16 12  6

14 21 17 24  4
10 16 15  9 19
18  8 23 26 20
22 11 13  6  5
 2  0 12  3  7"""

In [4]:
# test function on test data, sum should be 188 and product = 4512
calc_winning_score(day_4_test_nums, day_4_test_boards)

board number 2 has won:
[[14 21 17 24  4]
 [10 16 15  9 19]
 [18  8 23 26 20]
 [22 11 13  6  5]
 [ 2  0 12  3  7]]
[[1 1 1 1 1]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 1 0 0 1]
 [1 1 0 0 1]]
188


4512

In [5]:
# load full data 
with open('inputs/day_04_nums.txt') as f:
    day_4_nums = f.read()
    
with open('inputs/day_04_boards.txt') as f:
    day_4_boards = f.read()

In [6]:
# run through function for part 1
calc_winning_score(day_4_nums, day_4_boards)

board number 71 has won:
[[60 31 29 49 72]
 [89 41  5 79 22]
 [58 28 90 76 95]
 [93 45 14 47 37]
 [65 25  7 59 62]]
[[0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]]
1108


49860

Part 2: Figure out which board will win last. Once it wins, what would its final score be?

In [7]:
# function for part 2
def calc_last_winning_score(nums_string, boards_string):
    
    nums = [int(x) for x in nums_string.split(",")]
    
    boards_str_split = [y.split() for x in boards_string.split("\n\n") for y in x.split("\n")]
    boards = np.array(boards_str_split, dtype=int).reshape(-1,5,5)

    boards_tracker = np.zeros(shape=boards.shape, dtype=int)
    
    boards_list = list(range(boards.shape[0]))

    for num in nums:
        boards_won = []
        #print(num)
        for i in boards_list:
            boards_tracker[i] += boards[i] == num

            if max(boards_tracker[i].sum(axis=0)) == 5 or max(boards_tracker[i].sum(axis=1)) == 5:
                #print(f"board number {i} has won, after {num} was drawn")
                boards_won.append(i)
                #print(boards[i])
                #print(boards_tracker[i])
            
        for b in boards_won:
            boards_list.remove(b)
            
        if len(boards_list) == 0:
            last_board = boards_won[-1]
            print(f"The last board to win was number {last_board}, after {num} was drawn")
            unmarked_sum = sum(boards[last_board][boards_tracker[last_board] == 0])
            #print(unmarked_sum)
            #print(num)
        
            return unmarked_sum * num

In [8]:
# run on test data, 
# 2nd board (index 1) is last to win after 13 was drawn, final answer should be 1924
calc_last_winning_score(day_4_test_nums, day_4_test_boards)

The last board to win was number 1, after 13 was drawn


1924

In [9]:
# run on full data
calc_last_winning_score(day_4_nums, day_4_boards)

The last board to win was number 22, after 94 was drawn


24628